package de.doering.lib;

public enum TokenTypes {
    WIEDERHOLUNG_NULL_ZU_UNENDLICH,
    WIEDERHOLUNG_EINS_ZU_UNENDLICH,
    OPTION,
    WAHL,
    TERMINAL,
    NICHTTERMINAL,
    ANEINANDERREIHUNG,
    GRUPPE,
}

